import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {analyse} from '../lib/intelligence/analyse.js';
const sources=await Promise.all(['public-js/intelligence.js','public-js/filters.js','app.js'].map(p=>readFile(new URL('../'+p,import.meta.url),'utf8')));
class Node {
 children=[];textContent='';value='';checked=false;attributes={};classList={add(){},remove(){}};
 append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,f){this[k]=f;}showModal(){this.open=true;}close(){this.open=false;}focus(){}
 set innerHTML(v){throw Error('Unsafe HTML rendering');}
}
const text=n=>[n.textContent,...n.children.map(text)].join(' ');
function setup(){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);};const context=vm.createContext({fetch:async url=>Response.json(url==='/api/signals'?{success:true,count:0,signals:[]}:{success:true,companies:[]}),AbortController,URL,setTimeout,clearTimeout,document:{getElementById:get,createElement:()=>new Node(),createDocumentFragment:()=>new Node()}});sources.forEach(s=>vm.runInContext(s,context));return {context,get};}
const tick=()=>new Promise(r=>setImmediate(r));
test('dossier explains evidence gaps, unknown confidence and safe source handling',async()=>{const {context,get}=setup();await tick();const company={id:'c',name:'<img onerror=alert(1)>',website:'javascript:alert(1)'};context.payload={company,contacts:[],signals:[],intelligence:analyse(company)};vm.runInContext('renderDetail(payload)',context);assert.equal(get('detailTitle').textContent,company.name);const body=text(get('detailBody'));for(const phrase of ['Why now?','No strong recent buying signal','Risks / gaps','No sufficiently supported','Qualify first','Unknown'])assert.ok(body.includes(phrase),phrase);assert.ok(!body.includes('javascript:'));});
test('dossier highlights supported contact and exposes claim source',async()=>{const {context,get}=setup();await tick();const company={name:'Merchant',website:'https://example.com/',country:'Belgium',research_profile:{evidence:[{source_url:'https://example.com/',quote:'Merchant is a Belgian wine importer. New producers on 2026-09-01. Jane Doe, wine buyer, jane@example.com.'}]}};context.payload={company,contacts:[],signals:[],intelligence:analyse(company,[],[],new Date('2026-09-10'))};vm.runInContext('renderDetail(payload)',context);const body=text(get('detailBody'));assert.ok(body.includes('Jane Doe'));assert.ok(body.includes('Best person to contact'));assert.ok(body.includes('Contact evidence'));assert.ok(body.includes('generic')===false);});
test('country, type, opportunity, intent and contact filters compose',async()=>{const {context,get}=setup();await tick();context.rows=[{name:'A',country:'Belgium',company_type:'Importer',intelligence:{opportunity_score:80,buying_intent:70,has_decision_maker:true}},{name:'B',country:'France',company_type:'Importer',intelligence:{opportunity_score:90,buying_intent:80,has_decision_maker:true}},{name:'C',country:'Belgium',company_type:'Importer',intelligence:{opportunity_score:null,buying_intent:null}}];const r=vm.runInContext("filteredCompanies(rows,{country:'Belgium',type:'Importer',score:60,intent:50,contact:true})",context);assert.equal(r.map(c=>c.name).join(','),'A');});
test('recent signals and freshness sorting retain unknown last',async()=>{const {context}=setup();await tick();context.rows=[{name:'A',intelligence:{last_researched_at:'2026-01-01',has_recent_signal:true}},{name:'B',intelligence:{last_researched_at:null}},{name:'C',intelligence:{last_researched_at:'2026-09-01',has_recent_signal:true}}];assert.equal(vm.runInContext("filteredCompanies(rows,{sort:'researched'}).map(c=>c.name).join(',')",context),'C,A,B');assert.equal(vm.runInContext("filteredCompanies(rows,{recent:true}).length",context),2);});
test('filter changes render explicit empty result and preserve total',async()=>{const {context,get}=setup();await tick();context.rows=[{name:'A',country:'Belgium',opportunity_score:20}];vm.runInContext('setPipelineCompanies(rows)',context);get('filterScore').value='80';vm.runInContext('applyPipelineFilters()',context);assert.match(text(get('prospects')),/No companies match/);assert.equal(get('filterCount').textContent,'0 of 1 companies');});
